accounts: 
  - api_key: 086ab610a83b941968caea0e6cefd04e
    submission_interval: 60
    jobs:
      - id: Crittercism
        plugin: crittercism
        config:
          appId: "519d53101386202089000007"
          username: "username"
          password: "password"
          board:
            name: Crittercism
            prefix: crittercism